### PR TITLE
Feature: Add zk-index-refresh-current-query command

### PR DESCRIPTION
**Pull request by boyechko**
After doing some file modifications outside of ZK-Index, I often need to refresh
the currently narrowed list of files to see how they were affected by those
changes. To do that right now, one needs to zk-index-refresh followed up repeating all the focus/search query commands.

This is different from zk-index-current-notes, since the notes listed in ZK-Index have not necessarily been opened.

### CODE REVIEW

**Comment by localauthor** [comment]
First of all, I can't get this to work. For some reason, the variable only ever has one file in it.

Second, the function `zk-index--current-file-list` would seem to be useful in this case. Does the following function do what you're looking forward?

```elisp
(defun zk-index-query-refresh ()
  "Refresh current index, based on last focus or search queries."
  (interactive)
  (zk-index-refresh (zk-index--current-file-list)))
```

**Comment by boyechko** [comment]
Hmm, weird that it doesn't work, but your function does indeed do what I was hoping for, and without an extra variable. I think I got confused by `zk-index-current-notes` and `zk-index--current-file-list` meaning different things by "current," so didn't look at the latter function.

**Comment by localauthor** [comment]
Ok, I merged that function as zk-index-query-refresh, and bound it to 'g' in zk-index-mode-map

**Comment by localauthor** [comment]
Ah yes, naming things is hard :)

Speaking of, do you think zk-index-query-refresh is an alright name for this function?

**Pull request closed without merging**
