### PR TITLE
Add org-style links

### PR DESCRIPTION
**Pull request by jgru**
Dear Grant, 

this is an early draft for adding support for org-style links in the form of `zk:ID`. 
By utilizing this, one would benefit from full support of those links within `org` (e.g. for exporting), while avoiding the need to advice `org-open-at-point`. 

Do you think this could be beneficial? Looking forward to you thoughts on this. 

Best regards,
jgru

### CODE REVIEW

**Comment by localauthor** [comment]
I'll have to think through this a bit. Other than storing links, what are the benefits of using bona fide org-links?

**Comment by jgru** [comment]
Thanks for thinking about it. I anticipate the following benefits:
- Convenient linking via `org-store-link` and `org-insert-link` (as you already mentioned)
- Export of single notes via `ox-export` (not a strong argument)
- Jumping back to a previous position which is recorded by the commands following internal links (important and conventient imho)
- Using [search options](https://orgmode.org/manual/Search-Options.html)  

Do you think those intentions are legit or is it something for a private config?

**Comment by jgru** [comment]
It seems like it has something to do with org-mode.
Using the code in #8 solves the issue, didn't bother to figure it out in detail.

**Comment by localauthor** [comment]
> It seems like it has something to do with org-mode.
> Using the code in #8 solves the issue, didn't bother to figure it out in detail.

Hey, I'm not sure exactly what you mean by this. Which issue are you referring to?

**Comment by jgru** [comment]
> > It seems like it has something to do with org-mode.
> > Using the code in #8 solves the issue, didn't bother to figure it out in detail.
> 
> Hey, I'm not sure exactly what you mean by this. Which issue are you referring to?

Actually, I posted the comment in the wrong thread. Sorry for that. 
This code here (#8) solves the issues with `zk-index-view-note` (#3). 
Therefore, I closed that issue and reopened that PR, since I think that org-users would benefit from this addition given that `zk-index` works then as expected.

**Comment by localauthor** [comment]
I've rewritten and extended this in `zk-org-link.el`.

**Pull request closed without merging**
